/* Clubhouse service worker (SPEC §1.5). Owns the whole ./ scope, including the vendored apps.
   Release: bump CACHE_VERSION, then `node scripts/precache.mjs` (regenerates the SHELL list + js/version.js).

   Strategies
   - navigations ............ network-first, 2.5 s cap → cached page (./index.html, or the vendored app's index.html)
   - data/sports.json ....... network-first, 3 s cap → cached copy
   - ./apps/** assets ....... cache-first (vendored snapshots only change with a re-vendor + CACHE_VERSION bump)
   - other same-origin GET .. stale-while-revalidate
   - cross-origin ........... passed through, never cached
   On localhost every same-origin GET is network-first (so parallel development never sees stale files);
   offline behaviour is identical because the cache is the fallback. */

const CACHE_VERSION = 'clubhouse-v1-2026-09-28f';
const CACHE_PREFIX = 'clubhouse-';

// PRECACHE:BEGIN — generated by `node scripts/precache.mjs`; do not edit by hand.
const SHELL = [
  './',
  './index.html',
  './manifest.webmanifest',
  './css/base.css',
  './css/components.css',
  './css/screens.css',
  './css/sports.css',
  './css/tokens.css',
  './js/backup.js',
  './js/coach.js',
  './js/dates.js',
  './js/dom.js',
  './js/ls.js',
  './js/main.js',
  './js/pillars/_shared.js',
  './js/pillars/bourbon.js',
  './js/pillars/golf.js',
  './js/pillars/home.js',
  './js/pillars/index.js',
  './js/pillars/sports.js',
  './js/pillars/train.js',
  './js/recap.js',
  './js/router.js',
  './js/sample.js',
  './js/screens/_pillar-ui.js',
  './js/screens/_placeholder.js',
  './js/screens/backup.js',
  './js/screens/bourbon.js',
  './js/screens/golf.js',
  './js/screens/home.js',
  './js/screens/settings.js',
  './js/screens/sheet.js',
  './js/screens/sports.js',
  './js/screens/train-exercise.js',
  './js/screens/train-history.js',
  './js/screens/train-log.js',
  './js/screens/train.js',
  './js/store.js',
  './js/train/charts.js',
  './js/train/data.js',
  './js/train/form-import.js',
  './js/train/import-flow.js',
  './js/train/insights.js',
  './js/train/model.js',
  './js/train/settings-section.js',
  './js/train/source.js',
  './js/train/ui.js',
  './js/train/view.js',
  './js/ui.js',
  './js/vendor/golf-math.js',
  './js/vendor/shapes.js',
  './js/version.js',
  './fonts/barlow-condensed-600.woff2',
  './fonts/barlow-condensed-700.woff2',
  './icons/apple-touch-icon.png',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/icon.svg',
  './icons/maskable-512.png',
  './data/form-catalog.json',
  './data/sports.json',
];
// PRECACHE:END

// VENDORED:BEGIN — Lane B: each vendored app's former asset list, every path prefixed ./apps/<app>/.
// Generated by design/scripts/vendor-apps.mjs from each app's former service worker — do not edit by hand.
// Fairway Ledger's ?v= must match the vendored index.html exactly (the script asserts it).
const VENDORED = [
  './apps/fairway-ledger/',
  './apps/fairway-ledger/assets/maps/deerwood/aerial-2024.webp',
  './apps/fairway-ledger/index.html',
  './apps/fairway-ledger/clubhouse-bridge.css',
  './apps/fairway-ledger/clubhouse-bridge.js',
  './apps/fairway-ledger/styles.css?v=2026-07-29b',
  './apps/fairway-ledger/app.js?v=2026-07-29b',
  './apps/fairway-ledger/data/courses.js?v=2026-07-29b',
  './apps/fairway-ledger/data/course-maps/deerwood-runtime.js?v=2026-07-29b',
  './apps/fairway-ledger/lib/golf-math.js?v=2026-07-29b',
  './apps/fairway-ledger/lib/shapes.js?v=2026-07-29b',
  './apps/fairway-ledger/lib/voice-recap.js?v=2026-07-29b',
  './apps/fairway-ledger/lib/gps.js?v=2026-07-29b',
  './apps/fairway-ledger/lib/course-map.js?v=2026-07-29b',
  './apps/fairway-ledger/lib/course-map-labels.js?v=2026-07-29b',
  './apps/fairway-ledger/data/course-maps/deerwood-aerial-labels-v1.js?v=2026-07-29b',
  './apps/fairway-ledger/lib/course-map-ui.js?v=2026-07-29b',
  './apps/fairway-ledger/lib/games.js?v=2026-07-29b',
  './apps/fairway-ledger/icon.svg?v=2026-07-29b',
  './apps/barrel-proof/',
  './apps/barrel-proof/index.html',
  './apps/barrel-proof/styles.css',
  './apps/barrel-proof/icon.svg',
  './apps/barrel-proof/icon-192.png',
  './apps/barrel-proof/icon-512.png',
  './apps/barrel-proof/apple-touch-icon.png',
  './apps/barrel-proof/src/data/bottles.js',
  './apps/barrel-proof/src/data/friends.js',
  './apps/barrel-proof/src/data/cocktails.js',
  './apps/barrel-proof/src/data/reviews.js',
  './apps/barrel-proof/src/data/curated.js',
  './apps/barrel-proof/src/data/bottle-images.js',
  './apps/barrel-proof/src/logic/catalog.js',
  './apps/barrel-proof/src/logic/families.js',
  './apps/barrel-proof/src/logic/showdown.js',
  './apps/barrel-proof/src/logic/recommendation.js',
  './apps/barrel-proof/src/logic/palate.js',
  './apps/barrel-proof/src/logic/collection.js',
  './apps/barrel-proof/src/logic/prices.js',
  './apps/barrel-proof/src/logic/research.js',
  './apps/barrel-proof/src/logic/reviews.js',
  './apps/barrel-proof/src/logic/club.js',
  './apps/barrel-proof/src/logic/night.js',
  './apps/barrel-proof/src/logic/table-game.js',
  './apps/barrel-proof/src/ui/table-game.js',
  './apps/barrel-proof/src/ui/table-game.css',
  './apps/barrel-proof/src/logic/barcode.js',
  './apps/barrel-proof/src/logic/ratings.js',
  './apps/barrel-proof/vendor/zxing-library.min.js',
  './apps/barrel-proof/src/logic/cocktails.js',
  './apps/barrel-proof/src/storage/store.js',
  './apps/barrel-proof/src/ui/render.js',
  './apps/barrel-proof/src/main.js',
  './apps/barrel-proof/src/data/imported-catalog-index.json',
  './apps/barrel-proof/clubhouse-bridge.css',
  './apps/barrel-proof/clubhouse-bridge.js',
];
// VENDORED:END

const PRECACHE = [...SHELL, ...VENDORED];
const BASE = new URL('./', self.location).pathname; // '/clubhouse/' on Pages, '/' locally
const DEV = ['localhost', '127.0.0.1', '[::1]'].includes(self.location.hostname);
const APP_ROOTS = ['apps/fairway-ledger/', 'apps/barrel-proof/'];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_VERSION)
      .then((cache) => cache.addAll(PRECACHE.map((u) => new Request(u, { cache: 'reload' }))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith(CACHE_PREFIX) && k !== CACHE_VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

function rel(url) {
  return url.pathname.startsWith(BASE) ? url.pathname.slice(BASE.length) : null;
}

async function withTimeout(request, ms) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), ms);
  try {
    return await fetch(request, { signal: ctrl.signal });
  } finally {
    clearTimeout(timer);
  }
}

async function networkFirst(event, { ms, fallback, ignoreSearch = false }) {
  const req = event.request;
  const cache = await caches.open(CACHE_VERSION);
  try {
    const res = await withTimeout(req, ms);
    if (res && res.ok && res.type === 'basic') event.waitUntil(cache.put(req, res.clone()).catch(() => {}));
    if (res && (res.ok || !fallback)) return res;
    const hit = fallback ? await cache.match(fallback) : null;
    return hit || res;
  } catch (err) {
    const hit = (await cache.match(req, { ignoreSearch })) || (fallback ? await cache.match(fallback) : null);
    if (hit) return hit;
    return new Response('Offline and not cached yet.', { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
  }
}

async function cacheFirst(event) {
  const req = event.request;
  const cache = await caches.open(CACHE_VERSION);
  const hit = await cache.match(req);
  if (hit) return hit;
  const res = await fetch(req);
  if (res && res.ok && res.type === 'basic') event.waitUntil(cache.put(req, res.clone()).catch(() => {}));
  return res;
}

async function staleWhileRevalidate(event) {
  const req = event.request;
  const cache = await caches.open(CACHE_VERSION);
  const hit = await cache.match(req);
  const fresh = fetch(req).then((res) => {
    if (res && res.ok && res.type === 'basic') return cache.put(req, res.clone()).then(() => res, () => res);
    return res;
  });
  if (hit) {
    event.waitUntil(fresh.catch(() => {}));
    return hit;
  }
  return fresh;
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // cross-origin: pass through, never cached
  if (req.headers.has('range')) return;
  const path = rel(url);
  if (path == null) return; // outside our scope

  if (req.mode === 'navigate') {
    const app = APP_ROOTS.find((a) => path.startsWith(a));
    const fallback = app ? `${BASE}${app}index.html` : `${BASE}index.html`;
    event.respondWith(networkFirst(event, { ms: 2500, fallback, ignoreSearch: true }));
    return;
  }
  if (path === 'data/sports.json') {
    event.respondWith(networkFirst(event, { ms: 3000, ignoreSearch: true }));
    return;
  }
  if (DEV) {
    event.respondWith(networkFirst(event, { ms: 2500 }));
    return;
  }
  if (path.startsWith('apps/')) {
    event.respondWith(cacheFirst(event));
    return;
  }
  event.respondWith(staleWhileRevalidate(event));
});
